apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mi-pvc
  namespace: ipl
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
