apiVersion: v1
kind: PersistentVolume
metadata:
  name: mi-pv
spec:
  capacity:
    storage: 1Gi         # Total storage size
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce      # Can be mounted as R/W by a single node
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "/mnt/mi-shruti"
